# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0902071986267862d6bb521667edf0da96d4cf3f457d15df8feb0e03021022f913de3ebcf341d8d7646743df069d2a94bec48b58791605e032e9828c5b913e85

test:
  secret_key_base: 04d6ae6aa1945f448b674b55b2f22519ef16ee30632c4bc8da82b990543e0d96f4db5fd85fb7e940ebb957d04d2e0a969c9079efa1f920515863395aef120156

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
